spring :
  application :
    name : SpringTiendaWebCpe
  datasource :
    #url : jdbc:mariadb://localhost:3306/tienda?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/tienda?useSSL=false&serverTimezone=UTC
    username : root
    password :
