spring :
  application :
    name : SpringTiendaWebCpe
  datasource :
    #url : jdbc:mariadb://localhost:3306/tienda?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/tienda?useSSL=false&serverTimezone=UTC
    username : root
    password :

  security :
    user :
      name : root
      password : tecsup

app:
  storage:
    path: /Users/jgomez/var/data/
